// vocabularyLists.js
// Vocabulary lists for the rain game

const vocabularyLists = {
    1: [
        { word: '随便', translation: 'casual/whatever' },
        { word: '悠闲', translation: 'leisurely' },
        { word: '商贩', translation: 'vendor' },
        { word: '口渴', translation: 'thirsty' },
        { word: '玩意', translation: 'thingamabob' },
        { word: '节约', translation: 'save/economize' },
        { word: '卖', translation: 'sell' },
        { word: '药丸', translation: 'pill' },
        { word: '专用', translation: 'for exclusive use' },
        { word: '脆弱', translation: 'fragile' },
        { word: '隐藏', translation: 'hide' },
        { word: '修理', translation: 'repair/fix' },
        { word: '思量', translation: 'consider' },
        { word: '脑海', translation: 'mind (sea of thoughts)' },
        { word: '默默', translation: 'quietly' },
        { word: '某种', translation: 'a certain kind' },
        { word: '宝贝', translation: 'treasure' },
        { word: '井', translation: 'well' },
        { word: '撒哈拉', translation: 'Sahara' },
        { word: '承诺', translation: 'promise' },
        { word: '影子', translation: 'shadow' },
        { word: '圣诞树', translation: 'Christmas tree' },
        { word: '甜蜜', translation: 'sweet' },
        { word: '礼品', translation: 'gift' },
        { word: '却', translation: 'however' },
        { word: '光泽', translation: 'luster' },
        { word: '附近', translation: 'nearby' },
    ],
    2: [
       { word: '毒', translation: 'poison/poisonous' },
        { word: '闪电', translation: 'lightning' },
        { word: '咬', translation: 'to bite' },
        { word: '沙', translation: 'sand' },
        { word: '黎明', translation: 'dawn' },
        { word: '安慰', translation: 'comfort/console' },
        { word: '玻璃', translation: 'glass' },
        { word: '罩子', translation: 'cover' },
        { word: '辨认', translation: 'to identify' },
        { word: '返航', translation: 'return flight' },
        { word: '身躯', translation: 'body' },
        { word: '皮带', translation: 'belt' },
        { word: '风景', translation: 'scenery/landscape' },
        { word: '金黄色', translation: 'golden yellow' },
        { word: '准确', translation: 'accurate' },
        { word: '泪珠', translation: 'teardrop' },
        { word: '消失', translation: 'disappear' },
        { word: '以便', translation: 'so that' },
        { word: '从此', translation: 'from now on' },
        { word: '仔细', translation: 'attentive/careful' },
        { word: '匆匆', translation: 'hurriedly' },
        { word: '忐忑', translation: 'anxious/uneasy' }
    ],
    3: [
         { word: '悲伤', translation: 'sadness' },
        { word: '石墙', translation: 'stone wall' },
        { word: '脚印', translation: 'footprint' },
        { word: '留学生', translation: 'international student' },
        { word: '结束', translation: 'end' },
        { word: '性命', translation: 'life' },
        { word: '忧伤', translation: 'sorrow' },
        { word: '嘴套子', translation: 'muzzle' },
        { word: '受惊', translation: 'startled' },
        { word: '更加', translation: 'even more' },
        { word: '辘轳', translation: 'well pulley' },
        { word: '忍受', translation: 'endure' },
        { word: '甘泉', translation: 'sweet spring' },
        { word: '噩梦', translation: 'nightmare' },
        { word: '窗户', translation: 'window' },
        { word: '绳子', translation: 'rope' },
        { word: '将是', translation: 'will be' },
        { word: '到底', translation: 'after all/in the end' },
        { word: '既然', translation: 'since A then B' },
        { word: '被砍', translation: 'get chopped down' },
        { word: '铃铛', translation: 'bell' },
        { word: '犹豫', translation: 'hesitate' },
        { word: '缘故', translation: 'reason/cause' },
        { word: '大概', translation: 'probably' },
    ],
    4: [
        { word: '随便', translation: 'suí biàn' },
        { word: '悠闲', translation: 'yōu xián' },
        { word: '商贩', translation: 'shāng fàn' },
        { word: '口渴', translation: 'kǒu kě' },
        { word: '玩意', translation: 'wán yì' },
        { word: '节约', translation: 'jié yuē' },
        { word: '卖', translation: 'mài' },
        { word: '药丸', translation: 'yào wán' },
        { word: '专用', translation: 'zhuān yòng' },
        { word: '脆弱', translation: 'cuì ruò' },
        { word: '隐藏', translation: 'yǐn cáng' },
        { word: '修理', translation: 'xiū lǐ' },
        { word: '思量', translation: 'sī liang' },
        { word: '脑海', translation: 'nǎo hǎi' },
        { word: '默默', translation: 'mò mò' },
        { word: '某种', translation: 'mǒu zhǒng' },
        { word: '宝贝', translation: 'bǎo bèi' },
        { word: '井', translation: 'jǐng' },
        { word: '撒哈拉', translation: 'sā hā lā' },
        { word: '承诺', translation: 'chéng nuò' },
        { word: '影子', translation: 'yǐng zi' },
        { word: '圣诞树', translation: 'shèng dàn shù' },
        { word: '甜蜜', translation: 'tián mì' },
        { word: '礼品', translation: 'lǐ pǐn' },
        { word: '却', translation: 'què' },
        { word: '光泽', translation: 'guāng zé' },
        { word: '附近', translation: 'fù jìn' },
    ],
    5: [
        { word: '毒', translation: 'dú' },
        { word: '闪电', translation: 'shǎn diàn' },
        { word: '咬', translation: 'yǎo' },
        { word: '沙', translation: 'shā' },
        { word: '黎明', translation: 'lí míng' },
        { word: '安慰', translation: 'ān wèi' },
        { word: '玻璃', translation: 'bō li' },
        { word: '罩子', translation: 'zhào zi' },
        { word: '辨认', translation: 'biàn rèn' },
        { word: '返航', translation: 'fǎn háng' },
        { word: '身躯', translation: 'shēn qū' },
        { word: '皮带', translation: 'pí dài' },
        { word: '风景', translation: 'fēng jǐng' },
        { word: '金黄色', translation: 'jīn huáng sè' },
        { word: '准确', translation: 'zhǔn què' },
        { word: '泪珠', translation: 'lèi zhū' },
        { word: '消失', translation: 'xiāo shī' },
        { word: '以便', translation: 'yǐ biàn' },
        { word: '从此', translation: 'cóng cǐ' },
        { word: '仔细', translation: 'zǐ xì' },
        { word: '匆匆', translation: 'cōng cōng' },
        { word: '忐忑', translation: 'tǎn tè' }
    ],
    6: [
        { word: '悲伤', translation: 'bēi shāng' },
        { word: '石墙', translation: 'shí qiáng' },
        { word: '脚印', translation: 'jiǎo yìn' },
        { word: '留学生', translation: 'liú xué shēng' },
        { word: '结束', translation: 'jié shù' },
        { word: '性命', translation: 'xìng mìng' },
        { word: '忧伤', translation: 'yōu shāng' },
        { word: '嘴套子', translation: 'zuǐ tào zi' },
        { word: '受惊', translation: 'shòu jīng' },
        { word: '更加', translation: 'gèng jiā' },
        { word: '辘轳', translation: 'lù lu' },
        { word: '忍受', translation: 'rěn shòu' },
        { word: '甘泉', translation: 'gān quán' },
        { word: '噩梦', translation: 'è mèng' },
        { word: '窗户', translation: 'chuāng hu' },
        { word: '绳子', translation: 'shéng zi' },
        { word: '将是', translation: 'jiāng shì' },
        { word: '到底', translation: 'dào dǐ' },
        { word: '既然', translation: 'jì rán' },
        { word: '被砍', translation: 'bèi kǎn' },
        { word: '铃铛', translation: 'líng dāng' },
        { word: '犹豫', translation: 'yóu yù' },
        { word: '缘故', translation: 'yuán gù' },
        { word: '大概', translation: 'dà gài' },
    ],
    7: [
        { word: 'car', translation: 'coche' },
        { word: 'bus', translation: 'autobús' },
        { word: 'train', translation: 'tren' },
        { word: 'plane', translation: 'avión' },
        { word: 'boat', translation: 'barco' },
        { word: 'bicycle', translation: 'bicicleta' },
        { word: 'motorcycle', translation: 'motocicleta' },
        { word: 'truck', translation: 'camión' },
        { word: 'taxi', translation: 'taxi' },
        { word: 'subway', translation: 'metro' }
    ],
    8: [
        { word: 'one', translation: 'uno' },
        { word: 'two', translation: 'dos' },
        { word: 'three', translation: 'tres' },
        { word: 'four', translation: 'cuatro' },
        { word: 'five', translation: 'cinco' },
        { word: 'six', translation: 'seis' },
        { word: 'seven', translation: 'siete' },
        { word: 'eight', translation: 'ocho' },
        { word: 'nine', translation: 'nueve' },
        { word: 'ten', translation: 'diez' }
    ],
    9: [
        { word: 'head', translation: 'cabeza' },
        { word: 'hand', translation: 'mano' },
        { word: 'foot', translation: 'pie' },
        { word: 'eye', translation: 'ojo' },
        { word: 'ear', translation: 'oreja' },
        { word: 'nose', translation: 'nariz' },
        { word: 'mouth', translation: 'boca' },
        { word: 'arm', translation: 'brazo' },
        { word: 'leg', translation: 'pierna' },
        { word: 'finger', translation: 'dedo' }
    ]
};

// Export for use in the game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabularyLists;
}
