// vocabularyLists.js
// Vocabulary lists for the rain game

const vocabularyLists = {
    1: [
        { word: '大蟒蛇', translation: 'python' },
        { word: '动物', translation: 'animal' },
        { word: '冒险', translation: 'adventure' },
        { word: '完成', translation: 'complete' },
        { word: '一顶帽子', translation: 'a hat' },
        { word: '消化', translation: 'digestion' },
        { word: '大象', translation: 'elephant' },
        { word: '够', translation: 'enough' },
        { word: '理解', translation: 'understand' },
        { word: '沙漠', translation: 'desert' },
        { word: '任何', translation: 'any' },
        { word: '关乎生死', translation: 'concerning life and death' },
        { word: '绵羊', translation: 'wool sheep' },
        { word: '可惜', translation: 'too bad' },
        { word: '小家伙', translation: 'little fellow' },
    ],
    2: [
        { word: '大蟒蛇', translation: 'dà mǎng shé' },
        { word: '动物', translation: 'dòng wù' },
        { word: '冒险', translation: 'mào xiǎn' },
        { word: '完成', translation: 'wán chéng' },
        { word: '一顶帽子', translation: 'yī dǐng mào zi' },
        { word: '消化', translation: 'xiāo huà' },
        { word: '大象', translation: 'dà xiàng' },
        { word: '够', translation: 'gòu' },
        { word: '理解', translation: 'lǐ jiě' },
        { word: '沙漠', translation: 'shā mò' },
        { word: '任何', translation: 'rèn hé' },
        { word: '关乎生死', translation: 'guān hū shēng sǐ' },
        { word: '绵羊', translation: 'mián yáng' },
        { word: '可惜', translation: 'kě xī' },
        { word: '小家伙', translation: 'xiǎo jiā huò' },
    ],
    3: [
        { word: '除了', translation: 'apart from' },
        { word: '危险', translation: 'danger' },
        { word: '肚皮', translation: 'belly' },
        { word: '疑惑', translation: 'confuse/doubt' },
        { word: '一切', translation: 'everything' },
        { word: '希望', translation: 'hope' },
        { word: '秘密', translation: 'secret' },
        { word: '发现', translation: 'discover' },
        { word: '星球', translation: 'planet' },
        { word: '关于', translation: 'about' },
        { word: '一直', translation: 'always/straight' },
        { word: '轻', translation: 'light (weight)' },
        { word: '成功', translation: 'success' },
        { word: '望远镜', translation: 'telescope' },
        { word: '为了', translation: 'for the sake of' },
    ],
    4: [
        { word: '除了', translation: 'chú le' },
        { word: '危险', translation: 'wēi xiǎn' },
        { word: '肚皮', translation: 'dù pí' },
        { word: '疑惑', translation: 'yí huò' },
        { word: '一切', translation: 'yī qiè' },
        { word: '希望', translation: 'xī wàng' },
        { word: '秘密', translation: 'mì mì' },
        { word: '发现', translation: 'fā xiàn' },
        { word: '星球', translation: 'xīng qiú' },
        { word: '关于', translation: 'guān yú' },
        { word: '一直', translation: 'yī zhí' },
        { word: '轻', translation: 'qīng' },
        { word: '成功', translation: 'chéng gōng' },
        { word: '望远镜', translation: 'wàng yuǎn jìng' },
        { word: '为了', translation: 'wèi le' },
    ],
    5: [
        { word: '相反', translation: 'on the contrary' },
        { word: '论证', translation: 'argument/proof' },
        { word: '喜欢', translation: 'like' },
        { word: '读', translation: 'read' },
        { word: '相信', translation: 'believe' },
        { word: '一定', translation: 'definitely' },
        { word: '猴面包树', translation: 'baobab tree' },
        { word: '植物', translation: 'plant' },
        { word: '太阳', translation: 'sun' },
        { word: '必须', translation: 'must' },
        { word: '把', translation: 'particle (object marker)' },
        { word: '苗', translation: 'seedling' },
        { word: '一棵', translation: 'plants counter' },
        { word: '种子', translation: 'seed' },
        { word: '坏', translation: 'bad' },
    ],
    6: [
        { word: '相反', translation: 'xiāng fǎn' },
        { word: '论证', translation: 'lùn zhèng' },
        { word: '喜欢', translation: 'xǐ huān' },
        { word: '读', translation: 'dú' },
        { word: '相信', translation: 'xiāng xìn' },
        { word: '一定', translation: 'yī dìng' },
        { word: '猴面包树', translation: 'hóu miàn bāo shù' },
        { word: '植物', translation: 'zhí wù' },
        { word: '太阳', translation: 'tài yáng' },
        { word: '必须', translation: 'bì xū' },
        { word: '把', translation: 'bǎ' },
        { word: '苗', translation: 'miáo' },
        { word: '一棵', translation: 'yī kē' },
        { word: '种子', translation: 'zhǒng zi' },
        { word: '坏', translation: 'huài' },
    ],
    7: [
        { word: '日落', translation: 'sunset' },
        { word: '以为', translation: 'to think/assume' },
        { word: '苦闷', translation: 'depressed' },
        { word: '当时', translation: 'at that time' },
        { word: '开始', translation: 'start' },
        { word: '确实', translation: 'indeed' },
        { word: '片刻', translation: 'moment' },
        { word: '回答', translation: 'answer' },
        { word: '等待', translation: 'wait' },
        { word: '一颗螺丝', translation: 'one screw' },
        { word: '剌', translation: 'thorn' },
        { word: '一旦', translation: 'once A...' },
        { word: '反应', translation: 'reaction' },
        { word: '伤害', translation: 'harm' },
        { word: '惊讶', translation: 'surprised' },
    ],
    8: [
        { word: '日落', translation: 'rì luò' },
        { word: '以为', translation: 'yǐ wéi' },
        { word: '苦闷', translation: 'kǔ mèn' },
        { word: '当时', translation: 'dāng shí' },
        { word: '开始', translation: 'kāi shǐ' },
        { word: '确实', translation: 'què shí' },
        { word: '片刻', translation: 'piàn kè' },
        { word: '回答', translation: 'huí dá' },
        { word: '等待', translation: 'děng dài' },
        { word: '一颗螺丝', translation: 'yī kē luó sī' },
        { word: '剌', translation: 'là' },
        { word: '一旦', translation: 'yī dàn' },
        { word: '反应', translation: 'fǎn yìng' },
        { word: '伤害', translation: 'shāng hài' },
        { word: '惊讶', translation: 'jīng yà' },
    ],
    9: [
        { word: '难道', translation: 'rhetorical question marker' },
        { word: '应该', translation: 'should' },
        { word: '一朵花', translation: 'one flower' },
        { word: '了解', translation: 'understand' },
        { word: '颜色', translation: 'colour' },
        { word: '刚刚', translation: 'just now' },
        { word: '头发', translation: 'hair' },
        { word: '老虎', translation: 'tiger' },
        { word: '屏风', translation: 'screen' },
        { word: '复杂', translation: 'complex' },
        { word: '离开', translation: 'leave' },
        { word: '容易', translation: 'easy' },
        { word: '利用', translation: 'utilize' },
        { word: '蝴蝶', translation: 'butterfly' },
        { word: '干净', translation: 'clean' },
    ],
    10: [
        { word: '难道', translation: 'nán dào' },
        { word: '应该', translation: 'yīng gāi' },
        { word: '一朵花', translation: 'yī duǒ huā' },
        { word: '了解', translation: 'liǎo jiě' },
        { word: '颜色', translation: 'yán sè' },
        { word: '刚刚', translation: 'gāng gāng' },
        { word: '头发', translation: 'tóu fa' },
        { word: '老虎', translation: 'lǎo hǔ' },
        { word: '屏风', translation: 'píng fēng' },
        { word: '复杂', translation: 'fù zá' },
        { word: '离开', translation: 'lí kāi' },
        { word: '容易', translation: 'róng yì' },
        { word: '利用', translation: 'lì yòng' },
        { word: '蝴蝶', translation: 'hú dié' },
        { word: '干净', translation: 'gàn jìng' },
    ],
    11: [
        { word: '机会', translation: 'opportunity' },
        { word: '并不', translation: 'not at all' },
        { word: '麻烦', translation: 'hassle' },
        { word: '感冒', translation: 'cold/flu' },
        { word: '毛毛虫', translation: 'caterpillar' },
        { word: '决定', translation: 'decide' },
        { word: '打哈欠', translation: 'yawn' },
        { word: '命令', translation: 'command' },
        { word: '合理', translation: 'reasonable' },
        { word: '将军', translation: 'general' },
        { word: '统治', translation: 'rule' },
        { word: '服从', translation: 'obey' },
        { word: '使', translation: 'to cause' },
        { word: '审判', translation: 'judge' },
        { word: '老鼠', translation: 'mouse' },
    ],
    12: [
        { word: '机会', translation: 'jī huì' },
        { word: '并不', translation: 'bìng bù' },
        { word: '麻烦', translation: 'má fan' },
        { word: '感冒', translation: 'gǎn mào' },
        { word: '毛毛虫', translation: 'máo mao chóng' },
        { word: '决定', translation: 'jué dìng' },
        { word: '打哈欠', translation: 'dǎ hā qian' },
        { word: '命令', translation: 'mìng lìng' },
        { word: '合理', translation: 'hé lǐ' },
        { word: '将军', translation: 'jiāng jūn' },
        { word: '统治', translation: 'tǒng zhì' },
        { word: '服从', translation: 'fú cóng' },
        { word: '使', translation: 'shǐ' },
        { word: '审判', translation: 'shěn pàn' },
        { word: '老鼠', translation: 'lǎo shǔ' },
    ],
    13: [
        { word: '狂妄自负', translation: 'conceited' },
        { word: '崇拜者', translation: 'admirer' },
        { word: '鼓掌', translation: 'applaud' },
        { word: '向', translation: 'towards' },
        { word: '有趣', translation: 'interesting' },
        { word: '致意', translation: 'to salute' },
        { word: '左', translation: 'left' },
        { word: '眼睛', translation: 'eyes' },
        { word: '钦佩', translation: 'admire' },
        { word: '装满', translation: 'filled' },
        { word: '羞愧', translation: 'shame' },
        { word: '酒鬼', translation: 'drunkard' },
        { word: '访问', translation: 'visit' },
        { word: '帮助', translation: 'help' },
        { word: '迷惑', translation: 'bewildered' },
    ],
    14: [
        { word: '狂妄自负', translation: 'kuáng wàng zì fù' },
        { word: '崇拜者', translation: 'chóng bài zhě' },
        { word: '鼓掌', translation: 'gǔ zhǎng' },
        { word: '向', translation: 'xiàng' },
        { word: '有趣', translation: 'yǒu qù' },
        { word: '致意', translation: 'zhì yì' },
        { word: '左', translation: 'zuǒ' },
        { word: '眼睛', translation: 'yǎn jing' },
        { word: '钦佩', translation: 'qīn pèi' },
        { word: '装满', translation: 'zhuāng mǎn' },
        { word: '羞愧', translation: 'xiū kuì' },
        { word: '酒鬼', translation: 'jiǔ guǐ' },
        { word: '访问', translation: 'fǎng wèn' },
        { word: '帮助', translation: 'bāng zhù' },
        { word: '迷惑', translation: 'mí huò' },
    ],
    15: [
        { word: '桌', translation: 'table' },
        { word: '旁', translation: 'beside' },
        { word: '瓶子', translation: 'bottle' },
        { word: '五亿', translation: '500 million' },
        { word: '等于', translation: 'equal to' },
        { word: '放弃', translation: 'give up' },
        { word: '商人', translation: 'businessman' },
        { word: '胡思乱想', translation: 'wandering thoughts' },
        { word: '富', translation: 'rich' },
        { word: '属于', translation: 'belong to' },
        { word: '无主', translation: 'ownerless' },
        { word: '益处', translation: 'benefit' },
        { word: '一盏路灯', translation: 'streetlight' },
        { word: '点灯人', translation: 'lamplighter' },
        { word: '熄灭', translation: 'extinguish' },
    ],
    16: [
        { word: '桌', translation: 'zhuō' },
        { word: '旁', translation: 'páng' },
        { word: '瓶子', translation: 'píng zi' },
        { word: '五亿', translation: 'wǔ yì' },
        { word: '等于', translation: 'děng yú' },
        { word: '放弃', translation: 'fàng qì' },
        { word: '商人', translation: 'shāng rén' },
        { word: '胡思乱想', translation: 'hú sī luàn xiǎng' },
        { word: '富', translation: 'fù' },
        { word: '属于', translation: 'shǔ yú' },
        { word: '无主', translation: 'wú zhǔ' },
        { word: '益处', translation: 'yì chù' },
        { word: '一盏路灯', translation: 'yī zhǎn lù dēng' },
        { word: '点灯人', translation: 'diǎn dēng rén' },
        { word: '熄灭', translation: 'xī miè' },
    ],
    17: [
        { word: '职业', translation: 'occupation' },
        { word: '熄灯', translation: 'lights out' },
        { word: '改变', translation: 'change' },
        { word: '办法', translation: 'method' },
        { word: '圆圈', translation: 'circle' },
        { word: '保持', translation: 'maintain' },
        { word: '河流', translation: 'rivers' },
        { word: '专业', translation: 'major' },
        { word: '探险', translation: 'exploration' },
        { word: '如此', translation: 'so/in this way' },
        { word: '品德', translation: 'virtue' },
        { word: '调查', translation: 'investigate' },
        { word: '假使', translation: 'if/suppose' },
        { word: '记录', translation: 'record' },
        { word: '短暂', translation: 'brief time' },
    ],
    18: [
        { word: '职业', translation: 'zhí yè' },
        { word: '熄灯', translation: 'xī dēng' },
        { word: '改变', translation: 'gǎi biàn' },
        { word: '办法', translation: 'bàn fǎ' },
        { word: '圆圈', translation: 'yuán quān' },
        { word: '保持', translation: 'bǎo chí' },
        { word: '河流', translation: 'hé liú' },
        { word: '专业', translation: 'zhuān yè' },
        { word: '探险', translation: 'tàn xiǎn' },
        { word: '如此', translation: 'rú cǐ' },
        { word: '品德', translation: 'pǐn dé' },
        { word: '调查', translation: 'diào chá' },
        { word: '假使', translation: 'jiǎ shǐ' },
        { word: '记录', translation: 'jì lù' },
        { word: '短暂', translation: 'duǎn zàn' },
    ],
    19: [
        { word: '歌剧院', translation: 'opera house' },
        { word: '芭蕾舞', translation: 'ballet' },
        { word: '普通', translation: 'ordinary' },
        { word: '南极', translation: 'south pole' },
        { word: '包括', translation: 'include' },
        { word: '壮丽', translation: 'splendid' },
        { word: '大洲', translation: 'continent' },
        { word: '发明', translation: 'invent' },
        { word: '动作', translation: 'action' },
        { word: '孤独', translation: 'lonely' },
        { word: '沉默', translation: 'silent' },
        { word: '太平洋', translation: 'Pacific Ocean' },
        { word: '谜语', translation: 'riddle' },
        { word: '无聊', translation: 'bored' },
        { word: '手指', translation: 'finger' },
    ],
    20: [
        { word: '歌剧院', translation: 'gē jù yuàn' },
        { word: '芭蕾舞', translation: 'bā lěi wǔ' },
        { word: '普通', translation: 'pǔ tōng' },
        { word: '南极', translation: 'nán jí' },
        { word: '包括', translation: 'bā kuò' },
        { word: '壮丽', translation: 'zhuàng lì' },
        { word: '大洲', translation: 'dà zhōu' },
        { word: '发明', translation: 'fā míng' },
        { word: '动作', translation: 'dòng zuò' },
        { word: '孤独', translation: 'gū dú' },
        { word: '沉默', translation: 'chén mò' },
        { word: '太平洋', translation: 'tài píng yáng' },
        { word: '谜语', translation: 'mí yǔ' },
        { word: '无聊', translation: 'wú liáo' },
        { word: '手指', translation: 'shǒu zhǐ' },
    ],
    21: [
        { word: '计算', translation: 'calculation' },
        { word: '建议', translation: 'suggest' },
        { word: '广场', translation: 'square' },
        { word: '三枚花瓣', translation: 'three petals' },
        { word: '起眼', translation: 'eye-catching' },
        { word: '礼貌', translation: 'politeness' },
        { word: '曾经', translation: 'once did' },
        { word: '骆驼', translation: 'camel' },
        { word: '一支商队', translation: 'merchant caravan' },
        { word: '根', translation: 'roots' },
        { word: '大约', translation: 'approximately' },
        { word: '风吹', translation: 'wind blows' },
        { word: '想象力', translation: 'imagination' },
        { word: '峭壁', translation: 'cliff' },
        { word: '锋利', translation: 'sharp' },
    ],
    22: [
        { word: '计算', translation: 'jì suàn' },
        { word: '建议', translation: 'jiàn yì' },
        { word: '广场', translation: 'guǎng chǎng' },
        { word: '三枚花瓣', translation: 'sān méi huā bàn' },
        { word: '起眼', translation: 'qǐ yǎn' },
        { word: '礼貌', translation: 'lǐ mào' },
        { word: '曾经', translation: 'céng jīng' },
        { word: '骆驼', translation: 'luò tuo' },
        { word: '一支商队', translation: 'yī zhī shāng duì' },
        { word: '根', translation: 'gēn' },
        { word: '大约', translation: 'dà yuē' },
        { word: '风吹', translation: 'fēng chuī' },
        { word: '想象力', translation: 'xiǎng xiàng lì' },
        { word: '峭壁', translation: 'qiào bì' },
        { word: '锋利', translation: 'fēng lì' },
    ],
    23: [
        { word: '膝盖', translation: 'knee' },
        { word: '岩石', translation: 'rock' },
        { word: '凳子', translation: 'stool' },
        { word: '回声', translation: 'echo' },
        { word: '爬山', translation: 'climb mountain' },
        { word: '重复', translation: 'repeat' },
        { word: '独一无二', translation: 'one of a kind' },
        { word: '咳嗽', translation: 'cough' },
        { word: '宇宙', translation: 'universe' },
        { word: '永远', translation: 'forever' },
        { word: '玫瑰', translation: 'rose' },
        { word: '全部', translation: 'entire/all' },
        { word: '哭泣', translation: 'cry' },
        { word: '成为', translation: 'become' },
        { word: '伤心', translation: 'sad' },
    ],
    24: [
        { word: '膝盖', translation: 'xī gài' },
        { word: '岩石', translation: 'yán shí' },
        { word: '凳子', translation: 'dèng zi' },
        { word: '回声', translation: 'huí shēng' },
        { word: '爬山', translation: 'pá shān' },
        { word: '重复', translation: 'chóng fù' },
        { word: '独一无二', translation: 'dú yī wú èr' },
        { word: '咳嗽', translation: 'ké sou' },
        { word: '宇宙', translation: 'yǔ zhòu' },
        { word: '永远', translation: 'yǒng yuǎn' },
        { word: '玫瑰', translation: 'méi guī' },
        { word: '全部', translation: 'quán bù' },
        { word: '哭泣', translation: 'kū qì' },
        { word: '成为', translation: 'chéng wéi' },
        { word: '伤心', translation: 'shāng xīn' },
    ],
    25: [
        { word: '狐狸', translation: 'fox' },
        { word: '驯服', translation: 'tame' },
        { word: '千万', translation: 'millions' },
        { word: '猎人', translation: 'hunter' },
        { word: '脚步', translation: 'footsteps' },
        { word: '幸福', translation: 'happiness' },
        { word: '越...越', translation: 'more and more' },
        { word: '仪式', translation: 'ritual' },
        { word: '负责', translation: 'responsible' },
        { word: '扳道工', translation: 'track worker' },
        { word: '一批旅客', translation: 'group of passengers' },
        { word: '轰隆', translation: 'roaring' },
        { word: '追随', translation: 'follow' },
        { word: '寻找', translation: 'search' },
        { word: '列车', translation: 'train' },
    ],
    26: [
        { word: '狐狸', translation: 'hú li' },
        { word: '驯服', translation: 'xùn fú' },
        { word: '千万', translation: 'qiān wàn' },
        { word: '猎人', translation: 'liè rén' },
        { word: '脚步', translation: 'jiǎo bù' },
        { word: '幸福', translation: 'xìng fú' },
        { word: '越...越', translation: 'yuè...yuè' },
        { word: '仪式', translation: 'yí shì' },
        { word: '负责', translation: 'fù zé' },
        { word: '扳道工', translation: 'bān dào gōng' },
        { word: '一批旅客', translation: 'yī pī lǚ kè' },
        { word: '轰隆', translation: 'hōng lóng' },
        { word: '追随', translation: 'zhuī suí' },
        { word: '寻找', translation: 'xún zhǎo' },
        { word: '列车', translation: 'liè chē' },
    ],
    27: [
        { word: '满意', translation: 'satisfied' },
        { word: '过去', translation: 'past' },
        { word: '原来', translation: 'original' },
        { word: '随便', translation: 'casual/whatever' },
        { word: '悠闲', translation: 'leisurely' },
        { word: '商贩', translation: 'vendor' },
        { word: '口渴', translation: 'thirsty' },
        { word: '玩意', translation: 'thingamabob' },
        { word: '节约', translation: 'save/economize' },
        { word: '卖', translation: 'sell' },
        { word: '药丸', translation: 'pill' },
        { word: '专用', translation: 'exclusive use' },
        { word: '脆弱', translation: 'fragile' },
        { word: '隐藏', translation: 'hide' },
        { word: '修理', translation: 'repair' },
    ],
    28: [
        { word: '满意', translation: 'mǎn yì' },
        { word: '过去', translation: 'guò qù' },
        { word: '原来', translation: 'yuán lái' },
        { word: '随便', translation: 'suí biàn' },
        { word: '悠闲', translation: 'yōu xián' },
        { word: '商贩', translation: 'shāng fàn' },
        { word: '口渴', translation: 'kǒu kě' },
        { word: '玩意', translation: 'wán yì' },
        { word: '节约', translation: 'jié yuē' },
        { word: '卖', translation: 'mài' },
        { word: '药丸', translation: 'yào wán' },
        { word: '专用', translation: 'zhuān yòng' },
        { word: '脆弱', translation: 'cuì ruò' },
        { word: '隐藏', translation: 'yǐn cáng' },
        { word: '修理', translation: 'xiū lǐ' },
    ],
    29: [
        { word: '思量', translation: 'consider' },
        { word: '脑海', translation: 'mind' },
        { word: '默默', translation: 'quietly' },
        { word: '某种', translation: 'a certain kind' },
        { word: '宝贝', translation: 'treasure' },
        { word: '井', translation: 'well' },
        { word: '撒哈拉', translation: 'Sahara' },
        { word: '承诺', translation: 'promise' },
        { word: '影子', translation: 'shadow' },
        { word: '圣诞树', translation: 'Christmas tree' },
        { word: '甜蜜', translation: 'sweet' },
        { word: '礼品', translation: 'gift' },
        { word: '却', translation: 'however' },
        { word: '光泽', translation: 'luster' },
        { word: '附近', translation: 'nearby' },
    ],
    30: [
        { word: '思量', translation: 'sī liang' },
        { word: '脑海', translation: 'nǎo hǎi' },
        { word: '默默', translation: 'mò mò' },
        { word: '某种', translation: 'mǒu zhǒng' },
        { word: '宝贝', translation: 'bǎo bèi' },
        { word: '井', translation: 'jǐng' },
        { word: '撒哈拉', translation: 'sā hā lā' },
        { word: '承诺', translation: 'chéng nuò' },
        { word: '影子', translation: 'yǐng zi' },
        { word: '圣诞树', translation: 'shèng dàn shù' },
        { word: '甜蜜', translation: 'tián mì' },
        { word: '礼品', translation: 'lǐ pǐn' },
        { word: '却', translation: 'què' },
        { word: '光泽', translation: 'guāng zé' },
        { word: '附近', translation: 'fù jìn' },
    ],
    31: [
        { word: '悲伤', translation: 'sadness' },
        { word: '石墙', translation: 'stone wall' },
        { word: '脚印', translation: 'footprint' },
        { word: '留学生', translation: 'intl student' },
        { word: '结束', translation: 'end' },
        { word: '性命', translation: 'life' },
        { word: '忧伤', translation: 'sorrow' },
        { word: '嘴套子', translation: 'muzzle' },
        { word: '受惊', translation: 'startled' },
        { word: '更加', translation: 'even more' },
        { word: '辘轳', translation: 'well pulley' },
        { word: '忍受', translation: 'endure' },
        { word: '甘泉', translation: 'sweet spring' },
        { word: '噩梦', translation: 'nightmare' },
        { word: '窗户', translation: 'window' },
    ],
    32: [
        { word: '悲伤', translation: 'bēi shāng' },
        { word: '石墙', translation: 'shí qiáng' },
        { word: '脚印', translation: 'jiǎo yìn' },
        { word: '留学生', translation: 'liú xué shēng' },
        { word: '结束', translation: 'jié shù' },
        { word: '性命', translation: 'xìng mìng' },
        { word: '忧伤', translation: 'yōu shāng' },
        { word: '嘴套子', translation: 'zuǐ tào zi' },
        { word: '受惊', translation: 'shòu jīng' },
        { word: '更加', translation: 'gèng jiā' },
        { word: '辘轳', translation: 'lù lu' },
        { word: '忍受', translation: 'rěn shòu' },
        { word: '甘泉', translation: 'gān quán' },
        { word: '噩梦', translation: 'è mèng' },
        { word: '窗户', translation: 'chuāng hu' },
    ],
    33: [
        { word: '绳子', translation: 'rope' },
        { word: '将是', translation: 'will be' },
        { word: '到底', translation: 'after all' },
        { word: '既然', translation: 'since A then B' },
        { word: '被砍', translation: 'get chopped' },
        { word: '铃铛', translation: 'bell' },
        { word: '犹豫', translation: 'hesitate' },
        { word: '缘故', translation: 'reason' },
        { word: '大概', translation: 'probably' },
        { word: '毒', translation: 'poison' },
        { word: '闪电', translation: 'lightning' },
        { word: '咬', translation: 'to bite' },
        { word: '沙', translation: 'sand' },
        { word: '黎明', translation: 'dawn' },
        { word: '安慰', translation: 'comfort' },
    ],
    34: [
        { word: '绳子', translation: 'shéng zi' },
        { word: '将是', translation: 'jiāng shì' },
        { word: '到底', translation: 'dào dǐ' },
        { word: '既然', translation: 'jì rán' },
        { word: '被砍', translation: 'bèi kǎn' },
        { word: '铃铛', translation: 'líng dāng' },
        { word: '犹豫', translation: 'yóu yù' },
        { word: '缘故', translation: 'yuán gù' },
        { word: '大概', translation: 'dà gài' },
        { word: '毒', translation: 'dú' },
        { word: '闪电', translation: 'shǎn diàn' },
        { word: '咬', translation: 'yǎo' },
        { word: '沙', translation: 'shā' },
        { word: '黎明', translation: 'lí míng' },
        { word: '安慰', translation: 'ān wèi' },
    ],
    35: [
        { word: '玻璃', translation: 'glass' },
        { word: '罩子', translation: 'cover' },
        { word: '辨认', translation: 'identify' },
        { word: '返航', translation: 'return flight' },
        { word: '身躯', translation: 'body' },
        { word: '皮带', translation: 'belt' },
        { word: '风景', translation: 'scenery' },
        { word: '金黄色', translation: 'golden yellow' },
        { word: '准确', translation: 'accurate' },
        { word: '泪珠', translation: 'teardrop' },
        { word: '消失', translation: 'disappear' },
        { word: '以便', translation: 'so that' },
        { word: '从此', translation: 'from now on' },
        { word: '仔细', translation: 'attentive' },
        { word: '匆匆', translation: 'hurriedly' },
        { word: '忐忑', translation: 'anxious' },
    ],
    36: [
        { word: '玻璃', translation: 'bō li' },
        { word: '罩子', translation: 'zhào zi' },
        { word: '辨认', translation: 'biàn rèn' },
        { word: '返航', translation: 'fǎn háng' },
        { word: '身躯', translation: 'shēn qū' },
        { word: '皮带', translation: 'pí dài' },
        { word: '风景', translation: 'fēng jǐng' },
        { word: '金黄色', translation: 'jīn huáng sè' },
        { word: '准确', translation: 'zhǔn què' },
        { word: '泪珠', translation: 'lèi zhū' },
        { word: '消失', translation: 'xiāo shī' },
        { word: '以便', translation: 'yǐ biàn' },
        { word: '从此', translation: 'cóng cǐ' },
        { word: '仔细', translation: 'zǐ xì' },
        { word: '匆匆', translation: 'cōng cōng' },
        { word: '忐忑', translation: 'tǎn tè' },
    ]
};

// Export for use in the game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabularyLists;
}
